# Generated by Django 5.0.6 on 2024-09-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legkovoe_avto',
            old_name='model',
            new_name='parent',
        ),
    ]
